### ISSUE TITLE
How many promo links you can generate with one acc

### ISSUE THREAD

**Issue by ayaanmd100** [SuperSocket7/discord-promo-gen#2]
How many promo links you can generate with one acc

**Comment by SuperSocket7** [comment]
It seems to be able to generate basically unlimited

**Comment by ayaanmd100** [comment]
Uh, the promo links are the same

**Comment by ayaanmd100** [comment]
Nvm, Im stupid lol, I forgot to copy the end part of the link

**Comment by ayaanmd100** [comment]
Please, can you add proxy support too?

**Comment by SuperSocket7** [comment]
https://github.com/SuperSocket7/discord-promo-gen/commit/f19d7ccbd8a45e8fc60e6b852f4630e20289b60c
Probably could have been implemented.
